version: '3'
services:
  php7:
    container_name: phptips_php7
    ports:
      - "8080:80"
    build:
        context: "./docker/php"
        dockerfile: "Dockerfile"
    volumes:
        - .:/var/www/html
    networks:
      - phptips

  db:
    container_name: phptips_db
    ports:
     - "3306:3306"
    build:
        context: "./docker/mysql"
        dockerfile: "Dockerfile"        
    environment:
      MYSQL_DATABASE: phptips
      MYSQL_USER: phptips_user
      MYSQL_PASSWORD: phptips_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - phptips

networks:
  phptips:
    driver: "bridge"      