version: '3'
services:
  php:
    container_name: phptips_php
    ports:
      - "8080:80"
    build:
        context: "./docker/php"
        dockerfile: "Dockerfile"
    volumes:
        - .:/var/www/html
    networks:
      - phptips
  redis:
    container_name: phptips_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    networks:
      - phptips
  redisinsight:
    container_name: phptips_redisinsight  
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - ./redis/insight:/db
    networks:
      - phptips
  mailhog:
    container_name: phptips_mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    volumes:
     - "./mail/mhsendmail:/usr/local/bin/mhsendmail"
    networks:
      - phptips

  db:
    container_name: phptips_db
    ports:
     - "3306:3306"
    build:
        context: "./docker/mysql"
        dockerfile: "Dockerfile"        
    environment:
      MYSQL_DATABASE: phptips
      MYSQL_USER: phptips_user
      MYSQL_PASSWORD: phptips_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - phptips

networks:
  phptips:
    driver: "bridge"      